// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo-jjivOaUHal1ZEkD-9QRg6JAtK02k2I',
    appId: '1:122501981837:web:92638ba071f693b1c2a4c4',
    messagingSenderId: '122501981837',
    projectId: 'mudah-inap',
    authDomain: 'mudah-inap.firebaseapp.com',
    storageBucket: 'mudah-inap.appspot.com',
    measurementId: 'G-ZDS7SWZGBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOdY8mkfGQuQNbn7o4WOs-NIwXhthISvQ',
    appId: '1:122501981837:android:4d87797aeb9b798fc2a4c4',
    messagingSenderId: '122501981837',
    projectId: 'mudah-inap',
    storageBucket: 'mudah-inap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtngIJRRoqt2jSzHbdVHfkk-A1u22M-58',
    appId: '1:122501981837:ios:38e73633e73fdc2cc2a4c4',
    messagingSenderId: '122501981837',
    projectId: 'mudah-inap',
    storageBucket: 'mudah-inap.appspot.com',
    iosBundleId: 'com.example.courseHotel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtngIJRRoqt2jSzHbdVHfkk-A1u22M-58',
    appId: '1:122501981837:ios:aedbc44940b70756c2a4c4',
    messagingSenderId: '122501981837',
    projectId: 'mudah-inap',
    storageBucket: 'mudah-inap.appspot.com',
    iosBundleId: 'com.example.courseHotel.RunnerTests',
  );
}
